### ISSUE TITLE
Teams Selection Bug

### ISSUE THREAD

**Issue by RealJammy** [ractf/shell#10]
![image](https://user-images.githubusercontent.com/57639251/83434795-09a02900-a433-11ea-81b4-482ef357ff58.png)
After accessing the teams tab from here:
![image](https://user-images.githubusercontent.com/57639251/83434817-16248180-a433-11ea-9554-90bcb619f8b4.png)
It brings up the first error page. However, when I ctrl+f5 it, it fixes the issue. I was not part of a team when I accesed that page.
Thanks!

**Comment by Bottersnike** [comment]
Related: https://sentry.io/organizations/ractf/issues/1702842331/

**Comment by Bottersnike** [comment]
Doesn't appear to have re-appeared after a77c352. Closing for now.
