### ISSUE TITLE
Statistics page

### ISSUE THREAD

**Issue by thebeanogamer** [ractf/shell#19]
Make a page with some lovely Plotly/D3 visualisations of the data pumped out by the stats endpoint. Users, solves, etc.

**Comment by Bottersnike** [comment]
Ref: https://discordapp.com/channels/637760642173894677/706249593637306418/709447367799079305

**Comment by thebeanogamer** [comment]
You know that links to what I assume is Green aren't very helpful for people who aren't in it...

**Comment by Bentechy66** [comment]
It's a link to a message in green green whose entire contents are a link to another server that nobody can see
