### ISSUE TITLE
Implement dynamic scoring

### ISSUE THREAD

**Issue by NicholasG04** [ractf/shell#57]
- API broadcasts message with new points for challenge with new action_type, chall id and new score
- Shell updates this

Reference:
[Existing plugin](https://github.com/ractf/shell/blob/25de2d288b973735a777748ec5edffc3b04a99e0/src/plugins/websocketUpdates.js)
[Where challs are edited in store](https://github.com/ractf/shell/blob/25de2d288b973735a777748ec5edffc3b04a99e0/src/actions/challenges.js)
[How websockets work](https://github.com/ractf/shell/blob/master/src/controllers/WS.js#L82)

**Comment by thebeanogamer** [comment]
Resolved by #58
